version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./infra/php2/dockerfile
    volumes:
      - ./laravel:/work

  web:
    build:
      context: .
      dockerfile: ./infra/nginx/dockerfile
    image: nginx:1.18-alpine
    ports:
      - 80:80
    volumes:
      - ./laravel:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /laravel

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: