version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./infra/php2/Dockerfile
    volumes:
      - ./infra/php2/php-fpm.d:/var/run/php-fpm
      - ./laravel:/work/laravel

  web:
    build:
      context: .
      dockerfile: ./infra/nginx/Dockerfile
    image: nginx:1.18-alpine
    ports:
      - 80:80
    volumes:
      - ./infra/php2/php-fpm.d:/var/run/php-fpm
      - ./laravel:/work/laravel
    working_dir: /work/laravel

  db:
    build:
      context: .
      dockerfile: ./infra/mysql/Dockerfile
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: