version: "3"
services:
  app:
    build: ./infra/php2/
    volumes:
      - ./laravel:/work

  web:
    build: ./infra/nginx/
    image: nginx:1.18-alpine
    ports:
      - 80:80
    volumes:
      - ./laravel:/work
    working_dir: /laravel

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: