version: "3"
volumes:
  php-fpm-socket:
services:
  app:
    image: 411782827307.dkr.ecr.ap-northeast-1.amazonaws.com/laravel-app/php-fpm:latest

    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/auto-delivery-system/php-fpm
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: php-fpm

    volumes:
      - php-fpm-socket:/var/run/php-fpm

    env_file: .env.production

  web:
    ports:
      - 0:80
    image: 411782827307.dkr.ecr.ap-northeast-1.amazonaws.com/laravel-app/nginx:latest

    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/auto-delivery-system/nginx
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: nginx
    
    volumes:
      - php-fpm-socket:/var/run/php-fpm