# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.3.21-node-browsers
        environment:
          - APP_DEBUG: true
          - APP_ENV: testing
          - DB_HOST: 127.0.0.1
          - DB_CONNECTION: mysql
          - DB_DATABASE: default
          - DB_USERNAME: root
          - DB_PASSWORD: root
          - APP_KEY: base64:JUJ8UcbAJ2bFrUWRAKZPwWkoYhLN4DrTti7CEmsfPSc=

      - image: circleci/mysql:8.0.21
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: true
          - MYSQL_DATABASE: default
          - MYSQL_USER: root
          - MYSQL_ROOT_PASSWORD: root

    steps:
      - checkout

      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip pdo_mysql
      - run: sudo composer self-update

      - run:
          name: Wait for MySQL to be ready
          command: dockerize -wait tcp://localhost:3306 -timeout 2m

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "./laravel/composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          working_directory: /home/circleci/project/laravel
          command: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "./laravel/composer.json" }}
          paths:
            - ./vendor
      - restore_cache:
          keys:
            - node-v1-{{ checksum "./laravel/package.json" }}
            - node-v1-
      - run: yarn install
      - run:
          working_directory: /home/circleci/project/laravel
          command: php artisan migrate
      - run:
          working_directory: /home/circleci/project/laravel
          command: php artisan db:seed
      - run: 
          working_directory: /home/circleci/project/laravel
          command: vendor/phpunit/phpunit/phpunit
      - save_cache:
          key: node-v1-{{ checksum "./laravel/package.json" }}
          paths:
            - node_modules
