version: "3"
volumes:
  php-fpm-socket:
services:
  task:
    image: 411782827307.dkr.ecr.ap-northeast-1.amazonaws.com/laravel-app/php-fpm:latest

    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/auto-delivery-system/php-fpm/task
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: php-fpm/task